import Chart from "chart.js";
Chart.defaults.scale.ticks.fontSize = 10;
Chart.defaults.global.defaultFontSize = 10;
Chart.defaults.global.tooltips.backgroundColor = "rgba(0,0,0,0.5)";
Chart.defaults.global.tooltips.titleFontSize = 16;
Chart.defaults.global.tooltips.bodyFontStyle = 12;
Chart.defaults.global.tooltips.bodyFontStyle = "normal";
Chart.defaults.global.tooltips.footerFontSize = 12;
Chart.defaults.global.tooltips.xPadding = 6;
Chart.defaults.global.tooltips.yPadding = 6;
Chart.defaults.global.tooltips.cornerRadius = 10;
Chart.defaults.global.title.fontSize = 16;
export default Chart;